setwd("/run/media/black/wd/Codes/stat/report")
data <- read.csv("dota.csv")
summary(data)
attach(data)
hist(kills)
hist(assists)
hist(deaths)
hist(last_hits)
hist(denies)
hist(gpm)
hist(xpm)
hist(duration)
boxplot(gpm~skill)
boxplot(xpm~skill)
boxplot(kills~skill)
boxplot(assists~skill)
boxplot(deaths~skill)
boxplot(duration~skill)
boxplot(last_hits~skill)

wins <- table(match_result)
pie(wins)
library(ggplot2)
ggplot(data, aes(fill= match_result, y=3000, x=skill)) + geom_bar(position = "stack", stat="identity")

winskill <- table(match_result, skill)

barplot(winskill)
