## Mô hình hồi quy đa
Ở đây, chúng ta sẽ xây dựng một hàm để ước lượng khả năng thắng game dựa trên số lượt bị giết và số lượt giết của người chơi, cụ thể sẽ là mô hình hồi quy đa. Tuy nhiên, thông số cần được ước lượng là match_result chỉ với 2 giá trị 0 (thua) và 1 (thắng) trong bảng dữ liệu. Để tiện cho bài toán, ta xem giá trị match_value như số thực biểu diễn khả năng thắng game của người dùng, với giá trị càng lớn thì khả năng càng cao. Trong bài toán thực tế, sau khi xây dựng mô hình hồi quy đa, ta có thể "chuẩn hóa" lại giá trị match_value về {0, 1} bằng cách đặt giá trị threshold hoặc dùng các hàm activations, v.v...
```{R}
model_3<-lm(match_result~deaths+kills)
summary(model_3)
```
Mô hình được ước lượng là:
$\widehat{\text{match_result}}$ = 0.763233 - 0.072295 * deaths + 0.038415 * kills
(se)   0.013128   0.001418  0.001354
t   58.14   -50.99   28.38   

Ta kiểm định giả thuyết $\beta_1$ = 0 cho model_3:
$$\begin{cases}
H_0:\beta_1 = 0 \\ 
H_1: \beta_1 > 0
\end{cases} \text{ significane } \alpha = 0.05$$
```{R}
t_c1 = qt(1 - 0.5, df = 5997)
t_c1
```
$$t_c = 0 \\
t_{test~b_1} = 58.14 \Rightarrow t_{test~b_1} > t_c \Rightarrow \text{bác bỏ giả thuyết } H_0
$$

Ta kiểm định giả thuyết $\beta_2$ = 0 cho model_3:
$$\begin{cases}
H_0:\beta_2 = 0 \\ 
H_1: \beta_2 \neq 0
\end{cases} \text{ significane } \alpha = 0.05$$
```{R}
t_c2 = qt(1 - 0.5/2, df = 5997)
t_c2
```
$$t_c = 0.6745307 \\
t_{test~b_2} = -50.99 \Rightarrow |t_{test~b_2}| \geq t_c \Rightarrow \text{bác bỏ giả thuyết } H_0
$$
Ta kiểm định giả thuyết $\beta_3$ = 0 cho model_3:
$$\begin{cases}
H_0:\beta_3 = 0 \\ 
H_1: \beta_3 \neq 0
\end{cases} \text{ significane } \alpha = 0.05$$
```{R}
t_c2 = qt(1 - 0.5/2, df = 5997)
t_c2
```
$$t_c = 0.6745307 \\
t_{test~b_3} = 28.38 \Rightarrow |t_{test~b_3}| \geq t_c \Rightarrow \text{bác bỏ giả thuyết } H_0
$$
Kết luận:
$\widehat{\text{match_result}}$ = 0.763233 - 0.072295 * deaths + 0.038415 * kills
Ý nghĩa:
Mỗi lần số lần chết trong game tăng lên 1 lần thì khả năng thua game tăng thêm 0.072295 đơn vị
Mỗi lần số mạng giết được thêm trong game tăng 1 thì khả năng thắng game tăng thêm 0.038415

$\Rightarrow$ Điều này cho thấy rằng số mạng giết được trong game không có sức ảnh hưởng lớn bằng số lần bị chết trong game. Nói cách khác, giữ cho không bị giết quan trọng hơn đi săn...

Ước tính cụ thể:
```{R}
predict(model_3, data.frame(deaths = 1, kills = 8))
```
Nếu trong game chỉ chết đúng 1 lần nhưng giết được 8 thằng thì khả năng cao là game này sẽ thắng (0.9982571)
Xây dựng khoảng tin cậy 90% cho khả năng thắng game:
```{R}
confint(model_3, level = 0.9)
```
Khoảng ước lượng 90% cho hệ số $\beta_2:[-0.07462808, -0.06996275]$
Khoảng ước lượng 90% cho hệ số $\beta_3:[0.03618771, 0.04064212]$

```{R}
anova(model_3)
```
